# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  # can't use "gomod" because we don't commit the dagger generated code...
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
