# GitHub Actions Workflow definition to publish the Dagger modules to the Daggerverse.

name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: dagger_version
        uses: sagikazarmark/dagger-version-action
      - name: publish
        uses: dagger/dagger-for-github@v6
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          args: publish
